### ISSUE TITLE
Terminado

### ISSUE THREAD

**Issue by pxmpxmpurin** [ULL-ESIT-DMSI-1920/vue-fundamentals-alu0101227610#1]
He terminado lo que estaba solicitado, y además hice un botón para borrar el ultimo item. Además cambié un poco el CSS

**Comment by crguezl** [comment]
Añade el despliegue

**Comment by pxmpxmpurin** [comment]
https://ull-esit-dmsi-1920.github.io/vue-fundamentals-alu0101227610/

**Comment by crguezl** [comment]
@alu0101227610 
APTO
